spring:
  profiles:
    active: dev
  jpa:
    database: mysql

---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate