version: "3.1"

services:

  mysql-account:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=Account

  activemq:
    image: rmohr/activemq:5.15.6-alpine
    ports: 
      - "61616:61616"
      - "8161:8161"

  account-service:
    build: ./account
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql-account
      - BROKER_HOST=activemq
    depends_on:
      - "mysql-account"
      - "activemq"