version: "3.1"

services:

  mysql-account:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=Account

  mysql-video:
    image: mysql:latest
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Video

  activemq:
    image: rmohr/activemq:5.15.6-alpine
    ports: 
      - "61616:61616"
      - "8161:8161"

  mongodb:
    image: mvertes/alpine-mongo:latest
    ports: 
      - "27017:27017"

  account-service:
    build: ./account
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql-account
      - BROKER_HOST=activemq
    depends_on:
      - "mysql-account"
      - "activemq"

  video-service:
    build: ./video
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_HOST=mysql-video
      - BROKER_HOST=activemq
    depends_on:
      - "mysql-video"
      - "activemq"
      - "account-service"

  comments-service:
    build: ./comments
    ports:
      - "8082:8082"
    environment:
      - BROKER_HOST=activemq
      - DATABASE_HOST=mongodb
    depends_on:
      - "account-service"
      - "mongodb"
      - "video-service"
