spring:
  jpa:
    database: mysql
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8081
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  profiles: prod
  activemq:
    broker-url: tcp://${BROKER_HOST}:61616
    user: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:3306/Video
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 200000
      initialization-fail-timeout: 0