spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: Comments
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  port: 8082